
name: Timing Trigger

on:
  workflow_dispatch:
  schedule:
    - cron: 0 20 1,16 * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Trigger build
      uses: peter-evans/repository-dispatch@main
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Compile IPKs

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
